### ISSUE TITLE
[refactor] 이미지 저장에 관한 중복 코드 제거 및 리팩터링

### ISSUE THREAD

**Issue by Jaeyoung22** [woowacourse-teams/2023-trip-draw#150]
## 기능 설명
현재 감상 이미지 저장과 경로 이미지 저장 로직 중 중복되는 것이 있어서 이를 정리합니다.
추가로 다른 리팩터링도 진행합니다.

## 필요 태스크
- [x] 감상 이미지 저장과 경로 이미지 저장 중 중복되는 로직 제거
- [x] 기타 리팩터링

**Comment by greeng00se** [comment]
일단 기능 구현이 우선되어야 할 것 같아서 close 합니당~
