### ISSUE TITLE
[bug] 감상기록을 눌렀을 때 위치가 제대로 안나오는 것 같습니다.

### ISSUE THREAD

**Issue by no1msh** [woowacourse-teams/2023-trip-draw#207]
## 버그 사항
위치가 제대로 안나옵니다.
 

## 버그 simulation
1. 감상기록 버튼을 누릅니다.
2. 내 위치를 확인해보면 `서울 특별시 null`로 나옵니다.
 

## 원하던 상황
내 위치가 자세하게 나왔으면 좋겠습니다.
 

## **Screenshots**
![image](https://github.com/woowacourse-teams/2023-trip-draw/assets/22425650/abee191a-d0ac-403d-97f0-4f24cc30278c)

**Comment by otter66** [comment]
https://github.com/woowacourse-teams/2023-trip-draw/issues/211
알려주신 문제는 fix하였습니다~~ 
소중한 제보 감사합니다~~ 🌓
