### ISSUE TITLE
[refactor] Request, Response, DTO의 패키지 구조를 관리한다

### ISSUE THREAD

**Issue by beer-2000** [woowacourse-teams/2023-trip-draw#31]
## 기능 설명
- As-is : 루트 디렉토리에 dto 패키지 존재
- To-be : 협의를 통해, 모든 DTO의 패키지 구조를 정하고 적용한다.

## 필요 태스크
- [ ] dto 패키지 구조 협의
- [ ] 적용

**Comment by greeng00se** [comment]
현재 구조로 가는 걸로 결정했습니다.
