### ISSUE TITLE
[bug] 백그라운드에 두면 위치가 안 찍힘

### ISSUE THREAD

**Issue by Jaeyoung22** [woowacourse-teams/2023-trip-draw#327]
## 버그 사항
백그라운드에 두면 위치가 안 찍힘
 

## **Screenshots**
![ㅁㄴㅇㄹ](https://github.com/woowacourse-teams/2023-trip-draw/assets/89302528/98e51de0-cf64-4342-9ef1-972c7bfa0b5f)

**Comment by otter66** [comment]
해당 문제가 해결되었습니다. https://github.com/woowacourse-teams/2023-trip-draw/issues/414
