### ISSUE TITLE
감상이 있는 여행의 경우 여행 삭제가 안 되는 버그 수정

### ISSUE THREAD

**Issue by Combi153** [woowacourse-teams/2023-trip-draw#450]
## 기능 설명

현재 감상이 있는 여행의 경우 바로 여행 삭제가 안 됩니다.
감상을 모두 삭제한 이후에 여행을 삭제할 수 있습니다.
이를 수정하려고 합니다.
## 필요 태스크
- [ ] 여행 삭제 시 이벤트 발행으로 감상 삭제
- [ ] 감상 삭제 후 여행이 삭제될 수 있도록 변경

**Comment by Jaeyoung22** [comment]
이미 발행된 이슈입니다
