### ISSUE TITLE
[feat] 여행 단일 조회 api 구현 및 여행 상태 필드(Enum) 추가

### ISSUE THREAD

**Issue by Combi153** [woowacourse-teams/2023-trip-draw#87]
## 기능 설명
여행 단일 조회 시 사용할 api 를 구현한다
여행 상태를 나타내는 Enum을 만들고, 이를 Trip 필드에 추가한다

## 필요 태스크
- [x] 여행 단일 조회 api 구현
- [x] 여행 상태 열거형 TripEnum 구현
- [x] Trip에 필드 추가

**Comment by 2chang5** [comment]
후추도 라벨 ㅠㅠㅠ

**Comment by Combi153** [comment]
얼른 개발하고 싶은 마음에 그만..
주의하겠습니다..
